Metrics/AbcSize:
  base_points: 1_000_000
  overage_points: 70_000
Metrics/BlockNesting:
  remediation_points: 100_000
Metrics/ClassLength:
  base_points: 5_000_000
  overage_points: 35_000
Metrics/CyclomaticComplexity:
  base_points: 1_000_000
  overage_points: 70_000
Metrics/LineLength:
  remediation_points: 50_000
Metrics/MethodLength:
  base_points: 1_000_000
  overage_points: 70_000
Metrics/ModuleLength:
  base_points: 5_000_000
  overage_points: 35_000
Metrics/ParameterList:
  base_points: 500_000
  overage_points: 100_000
Metrics/PerceivedComplexity:
  base_points: 1_000_000
  overage_points: 70_000
