Metrics/AbcSize:
  violation_points: 100_000
Metrics/BlockNesting:
  base_points: 30_000
Metrics/ClassLength:
  base_points: 400_000
Metrics/CyclomaticComplexity:
  base_points: 75_000
  violation_points: 10_000
Metrics/LineLength:
  base_points: 20_000
  violation_points: 5_000
Metrics/MethodLength:
  base_points: 50_000
  violation_points: 10_000
Metrics/ModuleLength:
  base_points: 500_000
  violation_points: 5_000
Metrics/ParameterList:
  base_points: 10_000
  violation_points: 50_000
Metrics/PerceivedComplexity:
  base_points: 50_000
  violation_points: 5000
